name: Build LaTeX

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-pdf:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-fonts-extra

      - name: make pdf
        run: |
          make pdf

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cheat-Sheet.pdf
          path: cheat_sheets/build/*.pdf
          retention-days: 7

      - name: Deploy CV to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: cheat_sheets/build
          clean: true
          clean-exclude: index.html
          single-commit: true

      - name: Display logs
        if: always()
        run: |
          echo "::group:: Xvfb error 'xvfb_error.log'" && cat xvfb_error.log && echo "::endgroup::"
          echo "::group:: Terminal output 'console_output.txt'" && cat console_output.txt && echo "::endgroup::"
          for f in build/*.log; do echo "::group:: Output latex log file $f" && cat $f && echo "::endgroup::" ; done