name: Build LaTeX

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-pdf:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-fonts-extra

      - name: make pdf
        run: |
          make all

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cheat-Sheets
          path: build/*.pdf
          retention-days: 7

      - name: Deploy CV to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: cheat_sheets/build
          clean: true
          clean-exclude: index.html
          single-commit: true

      - name: Display logs
        if: always()
        run: |
          echo "::group:: Terminal output 'console_output.txt'" && cat console_output.txt && echo "::endgroup::"
          for f in build/*.log; do echo "::group:: Output latex log file $f" && cat $f && echo "::endgroup::" ; done

  release:
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [make-pdf]
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/download-artifact@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Cheat-Sheets/*.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true